### ISSUE TITLE
Size of the gauntlet

### ISSUE THREAD

**Issue by sjwilczynski** [codeshifu/react-thanos#1]
First let me say this is a very nice project. I just have one question. Is there a way to adjust the size of the gauntlet( to be inlined in large text or just two times smaller), e.g. in custom css file without cropping the original image and preserving your functionalities?

**Comment by codeshifu** [comment]
Hi @sjwilczynski, thanks for this suggestion. To answer your question

Is there a way to adjust the size of the gauntlet?
Currently, **no**.

Although it makes perfect sense to have the gauntlet resizable, I'm not sure if the animation will still work the way it does because the gauntlet is actually an [image sprite](https://www.w3schools.com/css/css_image_sprites.asp).

I love the idea of allowing users to resize the gauntlet for their use case & I should probably look into it. I wouldn't mind if you have any suggestions as to how it can be achieved or maybe you can submit a PR for it. 🙂

**Comment by sjwilczynski** [comment]
Thank you for your answer @codeshifu. For now I don't know how to do it, neither have I any suggestions. But if I come up with anything I will let you know.

**Comment by codeshifu** [comment]
Great! Looking forward to hearing from you soon.
